import type { Category } from '../types/category';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-rings',
    name: 'Rings',
    slug: 'rings',
    description: 'Solitaires, cocktail rings, eternity bands and more, crafted in fine metals and set with ethically-sourced stones.',
    image: 'category-rings',
    productCount: 5,
    status: 'active',
    sortOrder: 1,
  },
  {
    id: 'cat-engagement-rings',
    name: 'Engagement Rings',
    slug: 'engagement-rings',
    description: 'Solitaire and halo settings designed for the proposal moment.',
    image: 'category-engagement-rings',
    parentId: 'cat-rings',
    productCount: 2,
    status: 'active',
    sortOrder: 1,
  },
  {
    id: 'cat-wedding-bands',
    name: 'Wedding Bands',
    slug: 'wedding-bands',
    description: 'Classic and eternity bands for ceremonies and everyday wear.',
    image: 'category-wedding-bands',
    parentId: 'cat-rings',
    productCount: 2,
    status: 'active',
    sortOrder: 2,
  },
  {
    id: 'cat-necklaces',
    name: 'Necklaces',
    slug: 'necklaces',
    description: 'Pendants, tennis necklaces and chains for layering or statement wear.',
    image: 'category-necklaces',
    productCount: 5,
    status: 'active',
    sortOrder: 2,
  },
  {
    id: 'cat-earrings',
    name: 'Earrings',
    slug: 'earrings',
    description: 'Studs, drops and hoops in precious metals and gemstones.',
    image: 'category-earrings',
    productCount: 4,
    status: 'active',
    sortOrder: 3,
  },
  {
    id: 'cat-bracelets',
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Tennis bracelets, bangles and cuffs finished by hand.',
    image: 'category-bracelets',
    productCount: 4,
    status: 'active',
    sortOrder: 4,
  },
];
