import type { Product, ProductVariant } from '../types/product';

export const PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    slug: 'aurelia-solitaire-ring',
    name: 'Aurelia Solitaire Ring',
    description: 'A timeless round-brilliant solitaire set in platinum, designed to catch light from every angle.',
    category: 'Engagement Rings',
    categoryId: 'cat-engagement-rings',
    metal: 'platinum',
    gemstone: 'Diamond',
    price: 4800,
    compareAtPrice: 5200,
    images: ['aurelia-solitaire-ring-1', 'aurelia-solitaire-ring-2'],
    variants: [
      { id: 'prod-01-v1', metal: 'platinum', size: '5', sku: 'AUR-PLT-05', stock: 12 },
      { id: 'prod-01-v2', metal: 'platinum', size: '6', sku: 'AUR-PLT-06', stock: 8 },
      { id: 'prod-01-v3', metal: 'platinum', size: '7', sku: 'AUR-PLT-07', stock: 3 },
    ],
    totalStock: 23,
    lowStockThreshold: 5,
    status: 'active',
    isFeatured: true,
    rating: 4.9,
    costPrice: 2200,
    supplier: 'Meridian Gem Co.',
    internalNotes: 'Re-order lead time 6 weeks for platinum casting.',
    createdAt: '2025-09-04T09:12:00.000Z',
    updatedAt: '2026-06-18T14:30:00.000Z',
  },
  {
    id: 'prod-02',
    slug: 'celestine-halo-ring',
    name: 'Celestine Halo Ring',
    description: 'A cushion-cut center stone encircled by a shimmering halo of pave diamonds in white gold.',
    category: 'Engagement Rings',
    categoryId: 'cat-engagement-rings',
    metal: 'white-gold',
    gemstone: 'Diamond',
    price: 3600,
    images: ['celestine-halo-ring-1', 'celestine-halo-ring-2'],
    variants: [
      { id: 'prod-02-v1', metal: 'white-gold', size: '5', sku: 'CEL-WG-05', stock: 10 },
      { id: 'prod-02-v2', metal: 'white-gold', size: '6', sku: 'CEL-WG-06', stock: 4 },
    ],
    totalStock: 14,
    lowStockThreshold: 5,
    status: 'active',
    isFeatured: true,
    rating: 4.8,
    costPrice: 1500,
    supplier: 'Aurum Atelier',
    createdAt: '2025-10-11T10:05:00.000Z',
    updatedAt: '2026-07-02T11:00:00.000Z',
  },
  {
    id: 'prod-03',
    slug: 'vesper-eternity-band',
    name: 'Vesper Eternity Band',
    description: 'Channel-set diamonds circling a warm rose gold band, worn alone or stacked.',
    category: 'Wedding Bands',
    categoryId: 'cat-wedding-bands',
    metal: 'rose-gold',
    gemstone: 'Diamond',
    price: 2100,
    images: ['vesper-eternity-band-1'],
    variants: [
      { id: 'prod-03-v1', metal: 'rose-gold', size: '6', sku: 'VES-RG-06', stock: 15 },
      { id: 'prod-03-v2', metal: 'rose-gold', size: '7', sku: 'VES-RG-07', stock: 9 },
    ],
    totalStock: 24,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.7,
    costPrice: 950,
    supplier: 'Solstice Diamond House',
    createdAt: '2025-08-22T08:40:00.000Z',
    updatedAt: '2026-05-14T16:20:00.000Z',
  },
  {
    id: 'prod-04',
    slug: 'monarch-wedding-band',
    name: 'Monarch Wedding Band',
    description: 'A polished, comfort-fit yellow gold band built for everyday wear.',
    category: 'Wedding Bands',
    categoryId: 'cat-wedding-bands',
    metal: 'yellow-gold',
    price: 1200,
    images: ['monarch-wedding-band-1'],
    variants: [
      { id: 'prod-04-v1', metal: 'yellow-gold', size: '8', sku: 'MON-YG-08', stock: 20 },
      { id: 'prod-04-v2', metal: 'yellow-gold', size: '9', sku: 'MON-YG-09', stock: 14 },
      { id: 'prod-04-v3', metal: 'yellow-gold', size: '10', sku: 'MON-YG-10', stock: 0 },
    ],
    totalStock: 34,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.6,
    costPrice: 500,
    supplier: 'Heritage Stone Traders',
    createdAt: '2025-07-30T12:00:00.000Z',
    updatedAt: '2026-07-28T09:15:00.000Z',
  },
  {
    id: 'prod-05',
    slug: 'seraphine-cocktail-ring',
    name: 'Seraphine Cocktail Ring',
    description: 'A bold emerald centerpiece framed in warm yellow gold, made for statement occasions.',
    category: 'Rings',
    categoryId: 'cat-rings',
    metal: 'yellow-gold',
    gemstone: 'Emerald',
    price: 1850,
    images: ['seraphine-cocktail-ring-1'],
    variants: [{ id: 'prod-05-v1', metal: 'yellow-gold', size: '7', sku: 'SER-YG-07', stock: 6 }],
    totalStock: 6,
    lowStockThreshold: 5,
    status: 'draft',
    costPrice: 800,
    supplier: 'Aurum Atelier',
    internalNotes: 'Pending final photography before publishing.',
    createdAt: '2026-06-01T13:00:00.000Z',
    updatedAt: '2026-07-20T10:00:00.000Z',
  },
  {
    id: 'prod-06',
    slug: 'odessa-diamond-pendant',
    name: 'Odessa Diamond Pendant',
    description: 'A single brilliant-cut diamond suspended on a delicate white gold chain.',
    category: 'Necklaces',
    categoryId: 'cat-necklaces',
    metal: 'white-gold',
    gemstone: 'Diamond',
    price: 1650,
    images: ['odessa-diamond-pendant-1'],
    variants: [{ id: 'prod-06-v1', metal: 'white-gold', size: '16in', sku: 'ODE-WG-16IN', stock: 18 }],
    totalStock: 18,
    lowStockThreshold: 5,
    status: 'active',
    isNew: true,
    rating: 4.8,
    costPrice: 700,
    supplier: 'Meridian Gem Co.',
    createdAt: '2026-02-10T09:00:00.000Z',
    updatedAt: '2026-07-30T09:00:00.000Z',
  },
  {
    id: 'prod-07',
    slug: 'marchesa-tennis-necklace',
    name: 'Marchesa Tennis Necklace',
    description: 'A continuous line of platinum-set diamonds designed for red-carpet moments.',
    category: 'Necklaces',
    categoryId: 'cat-necklaces',
    metal: 'platinum',
    gemstone: 'Diamond',
    price: 4200,
    compareAtPrice: 4600,
    images: ['marchesa-tennis-necklace-1', 'marchesa-tennis-necklace-2'],
    variants: [{ id: 'prod-07-v1', metal: 'platinum', size: '17in', sku: 'MAR-PLT-17IN', stock: 5 }],
    totalStock: 5,
    lowStockThreshold: 5,
    status: 'active',
    isFeatured: true,
    rating: 4.9,
    costPrice: 1900,
    supplier: 'Solstice Diamond House',
    internalNotes: 'Re-order lead time 6 weeks; approve replenishment before next campaign.',
    createdAt: '2025-11-05T09:30:00.000Z',
    updatedAt: '2026-08-01T09:30:00.000Z',
  },
  {
    id: 'prod-08',
    slug: 'liora-pearl-drop-necklace',
    name: 'Liora Pearl Drop Necklace',
    description: 'A lustrous Akoya pearl drop on a fine yellow gold chain.',
    category: 'Necklaces',
    categoryId: 'cat-necklaces',
    metal: 'yellow-gold',
    gemstone: 'Pearl',
    price: 950,
    images: ['liora-pearl-drop-necklace-1'],
    variants: [{ id: 'prod-08-v1', metal: 'yellow-gold', size: '18in', sku: 'LIO-YG-18IN', stock: 25 }],
    totalStock: 25,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.5,
    costPrice: 400,
    supplier: 'Heritage Stone Traders',
    createdAt: '2025-09-28T11:20:00.000Z',
    updatedAt: '2026-04-11T11:20:00.000Z',
  },
  {
    id: 'prod-09',
    slug: 'valentina-sapphire-pendant',
    name: 'Valentina Sapphire Pendant',
    description: 'A rich cornflower sapphire framed by a diamond halo, set in white gold.',
    category: 'Necklaces',
    categoryId: 'cat-necklaces',
    metal: 'white-gold',
    gemstone: 'Sapphire',
    price: 2200,
    images: ['valentina-sapphire-pendant-1'],
    variants: [{ id: 'prod-09-v1', metal: 'white-gold', size: '16in', sku: 'VAL-WG-16IN', stock: 10 }],
    totalStock: 10,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.7,
    costPrice: 950,
    supplier: 'Aurum Atelier',
    createdAt: '2025-12-18T14:00:00.000Z',
    updatedAt: '2026-06-09T14:00:00.000Z',
  },
  {
    id: 'prod-10',
    slug: 'whisper-chain-necklace',
    name: 'Whisper Chain Necklace',
    description: 'An ultra-fine rose gold chain designed for everyday layering.',
    category: 'Necklaces',
    categoryId: 'cat-necklaces',
    metal: 'rose-gold',
    price: 650,
    images: ['whisper-chain-necklace-1'],
    variants: [{ id: 'prod-10-v1', metal: 'rose-gold', size: '20in', sku: 'WHI-RG-20IN', stock: 0 }],
    totalStock: 0,
    lowStockThreshold: 5,
    status: 'archived',
    costPrice: 280,
    supplier: 'Heritage Stone Traders',
    internalNotes: 'Discontinued line; sell through remaining stock only, do not reorder.',
    createdAt: '2025-08-01T08:00:00.000Z',
    updatedAt: '2026-03-15T08:00:00.000Z',
  },
  {
    id: 'prod-11',
    slug: 'grace-diamond-studs',
    name: 'Grace Diamond Studs',
    description: 'Classic four-prong diamond studs in platinum, a daily essential.',
    category: 'Earrings',
    categoryId: 'cat-earrings',
    metal: 'platinum',
    gemstone: 'Diamond',
    price: 2600,
    compareAtPrice: 2850,
    images: ['grace-diamond-studs-1'],
    variants: [{ id: 'prod-11-v1', metal: 'platinum', sku: 'GRA-PLT-001', stock: 7 }],
    totalStock: 7,
    lowStockThreshold: 5,
    status: 'active',
    isFeatured: true,
    rating: 4.9,
    costPrice: 1150,
    supplier: 'Meridian Gem Co.',
    createdAt: '2025-10-02T09:45:00.000Z',
    updatedAt: '2026-07-19T09:45:00.000Z',
  },
  {
    id: 'prod-12',
    slug: 'bellamy-drop-earrings',
    name: 'Bellamy Drop Earrings',
    description: 'Emerald-cut drops in yellow gold, elegant movement with every step.',
    category: 'Earrings',
    categoryId: 'cat-earrings',
    metal: 'yellow-gold',
    gemstone: 'Emerald',
    price: 1450,
    images: ['bellamy-drop-earrings-1'],
    variants: [{ id: 'prod-12-v1', metal: 'yellow-gold', sku: 'BEL-YG-001', stock: 13 }],
    totalStock: 13,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.6,
    costPrice: 620,
    supplier: 'Aurum Atelier',
    createdAt: '2025-11-22T10:15:00.000Z',
    updatedAt: '2026-05-30T10:15:00.000Z',
  },
  {
    id: 'prod-13',
    slug: 'isolde-hoop-earrings',
    name: 'Isolde Hoop Earrings',
    description: 'Slim polished hoops in rose gold, sized for everyday wear.',
    category: 'Earrings',
    categoryId: 'cat-earrings',
    metal: 'rose-gold',
    price: 780,
    images: ['isolde-hoop-earrings-1'],
    variants: [{ id: 'prod-13-v1', metal: 'rose-gold', sku: 'ISO-RG-001', stock: 0 }],
    totalStock: 0,
    lowStockThreshold: 5,
    status: 'archived',
    costPrice: 340,
    supplier: 'Solstice Diamond House',
    internalNotes: 'Archived due to low margin; do not reorder.',
    createdAt: '2025-08-15T12:30:00.000Z',
    updatedAt: '2026-02-20T12:30:00.000Z',
  },
  {
    id: 'prod-14',
    slug: 'noor-sapphire-earrings',
    name: 'Noor Sapphire Earrings',
    description: 'Pear-shaped sapphires set in white gold with a diamond accent.',
    category: 'Earrings',
    categoryId: 'cat-earrings',
    metal: 'white-gold',
    gemstone: 'Sapphire',
    price: 1350,
    images: ['noor-sapphire-earrings-1'],
    variants: [{ id: 'prod-14-v1', metal: 'white-gold', sku: 'NOO-WG-001', stock: 9 }],
    totalStock: 9,
    lowStockThreshold: 5,
    status: 'active',
    isNew: true,
    rating: 4.7,
    costPrice: 580,
    supplier: 'Meridian Gem Co.',
    createdAt: '2026-03-12T09:00:00.000Z',
    updatedAt: '2026-07-25T09:00:00.000Z',
  },
  {
    id: 'prod-15',
    slug: 'amara-tennis-bracelet',
    name: 'Amara Tennis Bracelet',
    description: 'A dazzling line of platinum-set diamonds designed to move with the wrist.',
    category: 'Bracelets',
    categoryId: 'cat-bracelets',
    metal: 'platinum',
    gemstone: 'Diamond',
    price: 3900,
    images: ['amara-tennis-bracelet-1', 'amara-tennis-bracelet-2'],
    variants: [
      { id: 'prod-15-v1', metal: 'platinum', size: '6.5in', sku: 'AMA-PLT-65IN', stock: 6 },
      { id: 'prod-15-v2', metal: 'platinum', size: '7in', sku: 'AMA-PLT-70IN', stock: 2 },
    ],
    totalStock: 8,
    lowStockThreshold: 5,
    status: 'active',
    isFeatured: true,
    rating: 4.9,
    costPrice: 1800,
    supplier: 'Solstice Diamond House',
    createdAt: '2025-09-19T10:00:00.000Z',
    updatedAt: '2026-08-02T10:00:00.000Z',
  },
  {
    id: 'prod-16',
    slug: 'delphine-bangle',
    name: 'Delphine Bangle',
    description: 'A sculptural, solid yellow gold bangle with a hidden clasp.',
    category: 'Bracelets',
    categoryId: 'cat-bracelets',
    metal: 'yellow-gold',
    price: 1550,
    images: ['delphine-bangle-1'],
    variants: [
      { id: 'prod-16-v1', metal: 'yellow-gold', size: 'S', sku: 'DEL-YG-S', stock: 11 },
      { id: 'prod-16-v2', metal: 'yellow-gold', size: 'M', sku: 'DEL-YG-M', stock: 8 },
    ],
    totalStock: 19,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.6,
    costPrice: 650,
    supplier: 'Heritage Stone Traders',
    createdAt: '2025-10-25T13:20:00.000Z',
    updatedAt: '2026-06-14T13:20:00.000Z',
  },
  {
    id: 'prod-17',
    slug: 'rosalind-charm-bracelet',
    name: 'Rosalind Charm Bracelet',
    description: 'A delicate rose gold chain ready for personalized charms.',
    category: 'Bracelets',
    categoryId: 'cat-bracelets',
    metal: 'rose-gold',
    price: 890,
    images: ['rosalind-charm-bracelet-1'],
    variants: [{ id: 'prod-17-v1', metal: 'rose-gold', size: '7in', sku: 'ROS-RG-70IN', stock: 16 }],
    totalStock: 16,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.5,
    costPrice: 380,
    supplier: 'Aurum Atelier',
    createdAt: '2025-12-01T15:00:00.000Z',
    updatedAt: '2026-05-05T15:00:00.000Z',
  },
  {
    id: 'prod-18',
    slug: 'silverleaf-cuff',
    name: 'Silverleaf Cuff',
    description: 'A hand-hammered sterling silver cuff with an organic, leaf-inspired texture.',
    category: 'Bracelets',
    categoryId: 'cat-bracelets',
    metal: 'silver',
    price: 450,
    images: ['silverleaf-cuff-1'],
    variants: [{ id: 'prod-18-v1', metal: 'silver', size: 'OS', sku: 'SIL-SLV-OS', stock: 4 }],
    totalStock: 4,
    lowStockThreshold: 5,
    status: 'draft',
    costPrice: 190,
    supplier: 'Heritage Stone Traders',
    createdAt: '2026-07-10T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((product) => product.id === id);
}

export function getLowStockVariants(): { product: Product; variant: ProductVariant }[] {
  return PRODUCTS.flatMap((product) =>
    product.variants
      .filter((variant) => variant.stock <= product.lowStockThreshold)
      .map((variant) => ({ product, variant }))
  );
}
